= Example Submodule

This is an example submodule to demonstrate:

* how the `classes().outsideOfProject()` filter works on different levels
* the AsciiDoc rendering

[plantuml, puml, png]
....
@startuml Write To AsciiDoc
!pragma useIntermediatePackages false

class "CarDto" as io.gitlab.plunts.gradle.plantuml.examples.dto.CarDto {
  +int getMaxPassengers()
  +void setMaxPassengers(int)
}
class "TruckDto" as io.gitlab.plunts.gradle.plantuml.examples.dto.TruckDto {
  +int getMaxLoad()
  +void setMaxLoad(int)
}
class "VehicleDto" as io.gitlab.plunts.gradle.plantuml.examples.dto.VehicleDto {
  +String getPlateNo()
  +boolean isRegistered()
  +List<TireDto> getTires()
  +SteeringWheelDto getSteeringWheel()
  +void setPlateNo(String)
  +void setRegistered(boolean)
  +void setTires(List<TireDto>)
  +void setSteeringWheel(SteeringWheelDto)
}
io.gitlab.plunts.gradle.plantuml.examples.dto.CarDto -u-|> io.gitlab.plunts.gradle.plantuml.examples.dto.VehicleDto
io.gitlab.plunts.gradle.plantuml.examples.dto.TruckDto -u-|> io.gitlab.plunts.gradle.plantuml.examples.dto.VehicleDto
@enduml
....

Here is some completly unrelated diagram which is not overwritten:

[plantuml, puml, png]
....
@startuml
(*) --> "First Activity"
"First Activity" --> (*)
@enduml
....
